# package manager
[[plugins]]
repo = 'Shougo/dein.vim'

# statusline plugin
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'kris89/vim-multiple-cursors'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 't9md/vim-choosewin'

[[plugins]]
repo = 'Yggdroot/LeaderF'

[[plugins]]
repo = 'scrooloose/nerdtree'

# LanguageServerProtocol
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_i = 1

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
