name: Installation and Setup Check

on: push

jobs:
  installation-and-setup-check:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: check brew package installation.
        run: make brew-bundle-ci
      - name: updates to dotfiles.
        run: make setup-dotfiles
      - name: updates to VSCode.
        run: make setup-vscode
      - name: check powerline-fonts installation.
        run: make install-powerline-fonts
      - name: check vim packages installation.
        run: make install-vim-packages
